import "./App.css";
import b1 from "./Assets/fan/b1.png";
import b2 from "./Assets/fan/b2.png";
import b3 from "./Assets/fan/b3.png";
import b4 from "./Assets/fan/b4.png";
import b5 from "./Assets/fan/b5.png";
import b6 from "./Assets/fan/b6.png";
import b7 from "./Assets/fan/b7.png";
import b8 from "./Assets/fan/b8.png";
import b9 from "./Assets/fan/b9.png";
import c1 from "./Assets/fan/c1.png";
import c2 from "./Assets/fan/c2.png";
import c3 from "./Assets/fan/c3.png";
import c4 from "./Assets/fan/c4.png";
import c5 from "./Assets/fan/c5.png";
import c6 from "./Assets/fan/c6.png";
import c7 from "./Assets/fan/c7.png";
import c8 from "./Assets/fan/c8.png";
import c9 from "./Assets/fan/c9.png";
import d1 from "./Assets/fan/d1.png";
import d2 from "./Assets/fan/d2.png";
import d3 from "./Assets/fan/d3.png";
import d4 from "./Assets/fan/d4.png";
import d5 from "./Assets/fan/d5.png";
import d6 from "./Assets/fan/d6.png";
import d7 from "./Assets/fan/d7.png";
import d8 from "./Assets/fan/d8.png";
import d9 from "./Assets/fan/d9.png";
import gd from "./Assets/fan/gd.png";
import rd from "./Assets/fan/rd.png";
import wd from "./Assets/fan/wd.png";
import e from "./Assets/fan/e.png";
import s from "./Assets/fan/s.png";
import w from "./Assets/fan/w.png";
import n from "./Assets/fan/n.png";
import front from "./Assets/fan/front.png";
import buf from "./Assets/fan/buf.png";
import Navbar from "./navbar.js";
import Fan from "./fan.js";
import SimpleFan from "./simple.js";
import React, { Component } from "react";

const tiles = [
  { id: 0, img: b1, alt: "Bamboo 1 Tile" },
  { id: 1, img: b2, alt: "Bamboo 2 Tile" },
  { id: 2, img: b3, alt: "Bamboo 3 Tile" },
  { id: 3, img: b4, alt: "Bamboo 4 Tile" },
  { id: 4, img: b5, alt: "Bamboo 5 Tile" },
  { id: 5, img: b6, alt: "Bamboo 6 Tile" },
  { id: 6, img: b7, alt: "Bamboo 7 Tile" },
  { id: 7, img: b8, alt: "Bamboo 8 Tile" },
  { id: 8, img: b9, alt: "Bamboo 9 Tile" },

  { id: 9, img: c1, alt: "Characters 1 Tile" },
  { id: 10, img: c2, alt: "Characters 2 Tile" },
  { id: 11, img: c3, alt: "Characters 3 Tile" },
  { id: 12, img: c4, alt: "Characters 4 Tile" },
  { id: 13, img: c5, alt: "Characters 5 Tile" },
  { id: 14, img: c6, alt: "Characters 6 Tile" },
  { id: 15, img: c7, alt: "Characters 7 Tile" },
  { id: 16, img: c8, alt: "Characters 8 Tile" },
  { id: 17, img: c9, alt: "Characters 9 Tile" },

  { id: 18, img: d1, alt: "Dots 1 Tile" },
  { id: 19, img: d2, alt: "Dots 2 Tile" },
  { id: 20, img: d3, alt: "Dots 3 Tile" },
  { id: 21, img: d4, alt: "Dots 4 Tile" },
  { id: 22, img: d5, alt: "Dots 5 Tile" },
  { id: 23, img: d6, alt: "Dots 6 Tile" },
  { id: 24, img: d7, alt: "Dots 7 Tile" },
  { id: 25, img: d8, alt: "Dots 8 Tile" },
  { id: 26, img: d9, alt: "Dots 9 Tile" },

  { id: 27, img: e, alt: "East Wind Tile" },
  { id: 28, img: s, alt: "South Wind Tile" },
  { id: 29, img: w, alt: "West Wind Tile" },
  { id: 30, img: n, alt: "North Wind Tile" },
  { id: 31, img: gd, alt: "Green Dragon Tile" },
  { id: 32, img: rd, alt: "Red Dragon Tile" },
  { id: 33, img: wd, alt: "White Dragon Tile" },

  { id: 34, img: front, alt: "Blank Tile" },
  {
    id: 35,
    img: buf,
    alt: "Buffer Tile representing mutliple inferrable tiles",
  },
];

const fans = [
  {
    name: "01. Big Four Winds",
    type: "honors",
    description: "Pungs of all winds",
    points: "88 pts",
    tiles: [
      tiles[27],
      tiles[27],
      tiles[27],
      tiles[28],
      tiles[28],
      tiles[28],
      tiles[29],
      tiles[29],
      tiles[29],
      tiles[30],
      tiles[30],
      tiles[30],
      tiles[34],
      tiles[34],
    ],
    exclusions:
      "Exclude Big Three Winds, All Pungs, Prevalent Wind, Seat Wind, Pung of Terminals or Honors",
  },
  {
    name: "02. Big Three Dragons",
    type: "honors",
    description: "Pungs of all dragons",
    points: "88 pts",
    tiles: [
      tiles[31],
      tiles[31],
      tiles[31],
      tiles[32],
      tiles[32],
      tiles[32],
      tiles[33],
      tiles[33],
      tiles[33],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Two Dragon Pungs, Dragon Pung",
  },
  {
    name: "03. All Green",
    type: "other",
    description: "All sets use only green tiles",
    points: "88 pts",
    tiles: [
      tiles[31],
      tiles[31],
      tiles[31],
      tiles[1],
      tiles[2],
      tiles[3],
      tiles[7],
      tiles[7],
      tiles[7],
      tiles[5],
      tiles[5],
      tiles[5],
      tiles[2],
      tiles[2],
    ],
    exclusions: "",
  },
  {
    name: "04. Nine Gates",
    type: "other",
    description:
      "Tiles 1, 1, 1, 2-8, 9, 9, 9 of one suit, with the last tile being any of the same suit",
    points: "88 pts",
    tiles: [
      tiles[9],
      tiles[9],
      tiles[9],
      tiles[10],
      tiles[11],
      tiles[12],
      tiles[13],
      tiles[14],
      tiles[15],
      tiles[16],
      tiles[17],
      tiles[17],
      tiles[17],
      tiles[14],
    ],
    exclusions:
      "Exclude Full Flush, Concealed Hand, Pung of Terminals or Honors, No Honors",
  },
  {
    name: "05. Four Kongs",
    type: "kongs",
    description: "Four kongs",
    points: "88 pts",
    tiles: [
      tiles[9],
      tiles[9],
      tiles[9],
      tiles[9],
      tiles[3],
      tiles[3],
      tiles[3],
      tiles[3],
      tiles[24],
      tiles[24],
      tiles[35],
      tiles[22],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Three Kongs, All Pungs, Single Wait",
  },
  {
    name: "06. Seven Shifted Pairs",
    type: "other",
    description:
      "Seven pairs of one suit, each pair shifted up one from the last",
    points: "88 pts",
    tiles: [
      tiles[2],
      tiles[2],
      tiles[3],
      tiles[3],
      tiles[4],
      tiles[4],
      tiles[5],
      tiles[5],
      tiles[6],
      tiles[6],
      tiles[7],
      tiles[7],
      tiles[8],
      tiles[8],
    ],
    exclusions:
      "Exclude Seven Pairs, Concealed Hand, Single Wait, No Honors, Full Flush",
  },
  {
    name: "07. Thirteen Orphans",
    type: "other",
    description:
      "One of each honor and terminal tile, plus any one tile to form a pair",
    points: "88 pts",
    tiles: [
      tiles[0],
      tiles[8],
      tiles[9],
      tiles[17],
      tiles[18],
      tiles[26],
      tiles[27],
      tiles[28],
      tiles[29],
      tiles[30],
      tiles[31],
      tiles[32],
      tiles[33],
      tiles[17],
    ],
    exclusions: "Exclude All Types, Concealed Hand, Single Wait",
  },
  {
    name: "08. All Terminals",
    type: "pungs",
    description: "All sets contain only 1s or 9s",
    points: "64 pts",
    tiles: [
      tiles[0],
      tiles[0],
      tiles[0],
      tiles[17],
      tiles[17],
      tiles[17],
      tiles[18],
      tiles[18],
      tiles[18],
      tiles[26],
      tiles[26],
      tiles[26],
      tiles[8],
      tiles[8],
    ],
    exclusions: "Exclude All Pungs, Outside Hand, Pung of Terminals or Honors",
  },
  {
    name: "09. Little Four Winds",
    type: "honors",
    description: "Three pungs of three winds, and a pair of the last wind",
    points: "64 pts",
    tiles: [
      tiles[27],
      tiles[27],
      tiles[27],
      tiles[29],
      tiles[29],
      tiles[29],
      tiles[30],
      tiles[30],
      tiles[30],
      tiles[28],
      tiles[28],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Pung of Terminals or Honors",
  },
  {
    name: "10. Little Three Dragons",
    type: "honors",
    description: "Two pungs of two dragons, and a pair of the last dragon",
    points: "64 pts",
    tiles: [
      tiles[31],
      tiles[31],
      tiles[31],
      tiles[33],
      tiles[33],
      tiles[33],
      tiles[32],
      tiles[32],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Two Dragon Pungs, Dragon Pung",
  },
  {
    name: "11. All Honors",
    type: "honors",
    description: "All sets contain only wind or dragon tiles",
    points: "64 pts",
    tiles: [
      tiles[31],
      tiles[31],
      tiles[31],
      tiles[27],
      tiles[27],
      tiles[27],
      tiles[29],
      tiles[29],
      tiles[29],
      tiles[30],
      tiles[30],
      tiles[30],
      tiles[32],
      tiles[32],
    ],
    exclusions: "Exclude All Pungs, Outside Hand, Pung of Terminals or Honors",
  },
  {
    name: "12. Four Concealed Pungs",
    type: "pungs",
    description: "Four unmelded pungs",
    points: "64 pts",
    tiles: [
      tiles[32],
      tiles[32],
      tiles[32],
      tiles[13],
      tiles[13],
      tiles[13],
      tiles[16],
      tiles[16],
      tiles[16],
      tiles[22],
      tiles[22],
      tiles[22],
      tiles[34],
      tiles[34],
    ],
    exclusions:
      "Exclude All Pungs, Concealed Hand, Three Concealed Pungs, Two Concealed Pungs",
  },
  {
    name: "13. Pure Terminal Chows",
    type: "chows",
    description:
      "Two of each terminal chow and a pair of 5s, all from the same suit",
    points: "64 pts",
    tiles: [
      tiles[9],
      tiles[10],
      tiles[11],
      tiles[9],
      tiles[10],
      tiles[11],
      tiles[15],
      tiles[16],
      tiles[17],
      tiles[15],
      tiles[16],
      tiles[17],
      tiles[13],
      tiles[13],
    ],
    exclusions:
      "Exclude Full Flush, All Chows, Pure Double Chow, Two Terminal Chows, No Honors",
  },
  {
    name: "14. Quadruple Chow",
    type: "chows",
    description: "Four identical chows of the same suit",
    points: "48 pts",
    tiles: [
      tiles[21],
      tiles[22],
      tiles[23],
      tiles[21],
      tiles[22],
      tiles[23],
      tiles[21],
      tiles[22],
      tiles[23],
      tiles[21],
      tiles[22],
      tiles[23],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Tile Hog, Pure Triple Chow, Pure Double Chow",
  },
  {
    name: "15. Four Pure Shifted Pungs",
    type: "pungs",
    description:
      "Four pungs of the same suit, each shifted up by one from the last",
    points: "48 pts",
    tiles: [
      tiles[13],
      tiles[13],
      tiles[13],
      tiles[14],
      tiles[14],
      tiles[14],
      tiles[15],
      tiles[15],
      tiles[15],
      tiles[16],
      tiles[16],
      tiles[16],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude All Pungs, Pure Shifted Pungs",
  },
  {
    name: "16. Four Pure Shifted Chows",
    type: "chows",
    description:
      "Four chows of the same suit, each shifted up by one or two from the last",
    points: "32 pts",
    tiles: [
      tiles[1],
      tiles[2],
      tiles[3],
      tiles[2],
      tiles[3],
      tiles[4],
      tiles[3],
      tiles[4],
      tiles[5],
      tiles[4],
      tiles[5],
      tiles[6],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Pure Shifted Chows, Two Terminal Chows",
  },
  {
    name: "17. Three Kongs",
    type: "kongs",
    description: "Three kongs",
    points: "32 pts",
    tiles: [
      tiles[2],
      tiles[2],
      tiles[2],
      tiles[2],
      tiles[13],
      tiles[13],
      tiles[13],
      tiles[13],
      tiles[17],
      tiles[17],
      tiles[17],
      tiles[17],
      tiles[35],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "18. All Terminals and Honors",
    type: "honors",
    description: "All sets contain only 1s, 9s, and honor tiles",
    points: "32 pts",
    tiles: [
      tiles[0],
      tiles[0],
      tiles[0],
      tiles[9],
      tiles[9],
      tiles[9],
      tiles[27],
      tiles[27],
      tiles[27],
      tiles[28],
      tiles[28],
      tiles[28],
      tiles[33],
      tiles[33],
    ],
    exclusions: "Exclude All Pungs, Outside Hand, Pung of Terminals or Honors",
  },
  {
    name: "19. Seven Pairs",
    type: "other",
    description: "Hand consists of just seven pairs",
    points: "24 pts",
    tiles: [
      tiles[3],
      tiles[3],
      tiles[6],
      tiles[6],
      tiles[9],
      tiles[9],
      tiles[22],
      tiles[22],
      tiles[23],
      tiles[23],
      tiles[26],
      tiles[26],
      tiles[27],
      tiles[27],
    ],
    exclusions: "Exclude Concealed Hand, Single Wait",
  },
  {
    name: "20. Greater Honors and Knitted Tiles",
    type: "other",
    description:
      "One of each honor tile, and all suits represented by interweaving",
    points: "24 pts",
    tiles: [
      tiles[0],
      tiles[3],
      tiles[6],
      tiles[10],
      tiles[16],
      tiles[20],
      tiles[23],
      tiles[27],
      tiles[28],
      tiles[29],
      tiles[30],
      tiles[31],
      tiles[32],
      tiles[33],
    ],
    exclusions: "Exclude Concealed Hand, All Types",
  },
  {
    name: "21. All Even Pungs",
    type: "pungs",
    description: "All sets composed only with even tiles",
    points: "24 pts",
    tiles: [
      tiles[1],
      tiles[1],
      tiles[1],
      tiles[7],
      tiles[7],
      tiles[7],
      tiles[12],
      tiles[12],
      tiles[12],
      tiles[16],
      tiles[16],
      tiles[16],
      tiles[25],
      tiles[25],
    ],
    exclusions: "Exclude All Pungs, All Simples, No Honors",
  },
  {
    name: "22. Full Flush",
    type: "other",
    description: "All sets composed of tiles from a single suit",
    points: "24 pts",
    tiles: [
      tiles[18],
      tiles[19],
      tiles[20],
      tiles[23],
      tiles[24],
      tiles[25],
      tiles[21],
      tiles[21],
      tiles[21],
      tiles[26],
      tiles[26],
      tiles[26],
      tiles[18],
      tiles[18],
    ],
    exclusions: "Exclude No Honors",
  },
  {
    name: "23. Pure Triple Chow",
    type: "chows",
    description: "Three identical chows of one suit",
    points: "24 pts",
    tiles: [
      tiles[11],
      tiles[12],
      tiles[13],
      tiles[11],
      tiles[12],
      tiles[13],
      tiles[11],
      tiles[12],
      tiles[13],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Pure Double Chow",
  },
  {
    name: "24. Pure Shifted Pungs",
    type: "pungs",
    description:
      "Three pungs of the same suit, each shifted up by one from the last",
    points: "24 pts",
    tiles: [
      tiles[20],
      tiles[20],
      tiles[20],
      tiles[21],
      tiles[21],
      tiles[21],
      tiles[22],
      tiles[22],
      tiles[22],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude All Pungs",
  },
  {
    name: "25. Upper Tiles",
    type: "other",
    description: "All sets use only 7s, 8s, and/or 9s",
    points: "24 pts",
    tiles: [
      tiles[6],
      tiles[7],
      tiles[8],
      tiles[15],
      tiles[15],
      tiles[15],
      tiles[24],
      tiles[25],
      tiles[26],
      tiles[24],
      tiles[25],
      tiles[26],
      tiles[7],
      tiles[7],
    ],
    exclusions: "Exclude Upper Four, No Honors",
  },
  {
    name: "26. Middle Tiles",
    type: "other",
    description: "All sets use only 4s, 5s, and/or 6s",
    points: "24 pts",
    tiles: [
      tiles[3],
      tiles[3],
      tiles[3],
      tiles[5],
      tiles[5],
      tiles[5],
      tiles[12],
      tiles[13],
      tiles[14],
      tiles[23],
      tiles[23],
      tiles[23],
      tiles[13],
      tiles[13],
    ],
    exclusions: "Exclude All Simples, No Honors",
  },
  {
    name: "27. Lower Tiles",
    type: "other",
    description: "All sets use only 1s, 2s, and/or 3s",
    points: "24 pts",
    tiles: [
      tiles[1],
      tiles[1],
      tiles[1],
      tiles[9],
      tiles[10],
      tiles[11],
      tiles[10],
      tiles[10],
      tiles[10],
      tiles[18],
      tiles[19],
      tiles[20],
      tiles[19],
      tiles[19],
    ],
    exclusions: "Exclude Lower Four, No Honors",
  },
  {
    name: "28. Pure Straight",
    type: "chows",
    description:
      "Three consecutive chows of one suit forming a sequence from 1-9",
    points: "16 pts",
    tiles: [
      tiles[9],
      tiles[10],
      tiles[11],
      tiles[12],
      tiles[13],
      tiles[14],
      tiles[15],
      tiles[16],
      tiles[17],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Short Straight, Two Terminal Chows",
  },
  {
    name: "29. Three-Suited Terminal Chows",
    type: "chows",
    description:
      "Both terminal chows from two suits, and a pair of 5s from the last suit",
    points: "16 pts",
    tiles: [
      tiles[9],
      tiles[10],
      tiles[11],
      tiles[15],
      tiles[16],
      tiles[17],
      tiles[18],
      tiles[19],
      tiles[20],
      tiles[24],
      tiles[25],
      tiles[26],
      tiles[4],
      tiles[4],
    ],
    exclusions:
      "Exclude All Chows, Mixed Double Chow, Two Terminal Chows, No Honors",
  },
  {
    name: "30. Pure Shifted Chows",
    type: "chows",
    description:
      "Three chows of one suit, each shifted up by one or two from the last",
    points: "16 pts",
    tiles: [
      tiles[19],
      tiles[20],
      tiles[21],
      tiles[20],
      tiles[21],
      tiles[22],
      tiles[21],
      tiles[22],
      tiles[23],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "31. All Fives",
    type: "other",
    description: "All sets contain at least one 5",
    points: "16 pts",
    tiles: [
      tiles[2],
      tiles[3],
      tiles[4],
      tiles[3],
      tiles[4],
      tiles[5],
      tiles[12],
      tiles[13],
      tiles[14],
      tiles[22],
      tiles[22],
      tiles[22],
      tiles[13],
      tiles[13],
    ],
    exclusions: "Exclude All Simples, No Honors",
  },
  {
    name: "32. Triple Pung",
    type: "pungs",
    description: "Three pungs of the same number, one in each suit",
    points: "16 pts",
    tiles: [
      tiles[4],
      tiles[4],
      tiles[4],
      tiles[13],
      tiles[13],
      tiles[13],
      tiles[22],
      tiles[22],
      tiles[22],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Double Pungs",
  },
  {
    name: "33. Three Concealed Pungs",
    type: "pungs",
    description: "Three pungs achieved without melding",
    points: "16 pts",
    tiles: [
      tiles[4],
      tiles[4],
      tiles[4],
      tiles[11],
      tiles[11],
      tiles[11],
      tiles[31],
      tiles[31],
      tiles[31],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Two Concealed Pungs",
  },
  {
    name: "34. Lesser Honors and Knitted Tiles",
    type: "other",
    description:
      "5 or 6 honor tiles, and all suits represented by interweaving",
    points: "12 pts",
    tiles: [
      tiles[0],
      tiles[3],
      tiles[6],
      tiles[10],
      tiles[13],
      tiles[16],
      tiles[20],
      tiles[23],
      tiles[27],
      tiles[28],
      tiles[29],
      tiles[30],
      tiles[31],
      tiles[32],
    ],
    exclusions: "Exclude Two Concealed Pungs",
  },
  {
    name: "35. Knitted Straight",
    type: "other",
    description: "A full sequence in all suits represented by interweaving",
    points: "12 pts",
    tiles: [
      tiles[0],
      tiles[3],
      tiles[6],
      tiles[10],
      tiles[13],
      tiles[16],
      tiles[20],
      tiles[23],
      tiles[26],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "36. Upper Four",
    type: "other",
    description: "All sets use only 6s, 7s, 8s, and/or 9s",
    points: "12 pts",
    tiles: [
      tiles[5],
      tiles[6],
      tiles[7],
      tiles[6],
      tiles[7],
      tiles[8],
      tiles[15],
      tiles[15],
      tiles[15],
      tiles[17],
      tiles[17],
      tiles[17],
      tiles[26],
      tiles[26],
    ],
    exclusions: "Exclude No Honors",
  },
  {
    name: "37. Lower Four",
    type: "other",
    description: "All sets use only 1s, 2s, 3s, and/or 4s",
    points: "12 pts",
    tiles: [
      tiles[0],
      tiles[0],
      tiles[0],
      tiles[1],
      tiles[2],
      tiles[3],
      tiles[11],
      tiles[11],
      tiles[11],
      tiles[19],
      tiles[20],
      tiles[21],
      tiles[19],
      tiles[19],
    ],
    exclusions: "Exclude No Honors",
  },
  {
    name: "38. Big Three Winds",
    type: "honors",
    description: "Three pungs of winds",
    points: "12 pts",
    tiles: [
      tiles[28],
      tiles[28],
      tiles[28],
      tiles[29],
      tiles[29],
      tiles[29],
      tiles[30],
      tiles[30],
      tiles[30],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Pung of Terminals or Honors",
  },
  {
    name: "39. Mixed Straight",
    type: "chows",
    description:
      "Three consecutive chows, one from each suit, forming a sequence from 1-9",
    points: "8 pts",
    tiles: [
      tiles[0],
      tiles[1],
      tiles[2],
      tiles[12],
      tiles[13],
      tiles[14],
      tiles[24],
      tiles[25],
      tiles[26],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "40. Reversible Tiles",
    type: "other",
    description: "All sets use only vertically symmetric tiles",
    points: "8 pts",
    tiles: [
      tiles[1],
      tiles[1],
      tiles[1],
      tiles[7],
      tiles[7],
      tiles[7],
      tiles[18],
      tiles[19],
      tiles[20],
      tiles[20],
      tiles[21],
      tiles[22],
      tiles[33],
      tiles[33],
    ],
    exclusions: "Exclude One Voided Suit",
  },
  {
    name: "41. Mixed Triple Chow",
    type: "chows",
    description: "Three identical chows, one from each suit",
    points: "8 pts",
    tiles: [
      tiles[1],
      tiles[2],
      tiles[3],
      tiles[10],
      tiles[11],
      tiles[12],
      tiles[19],
      tiles[20],
      tiles[21],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude One Voided Suit",
  },
  {
    name: "42. Mixed Shifted Pungs",
    type: "pungs",
    description:
      "Three pungs, one from each suit, each shifted up by one from the last",
    points: "8 pts",
    tiles: [
      tiles[5],
      tiles[5],
      tiles[5],
      tiles[15],
      tiles[15],
      tiles[15],
      tiles[25],
      tiles[25],
      tiles[25],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "43. Chicken Hand",
    type: "other",
    description: "Any hand that does not receive any points from any other fan",
    points: "8 pts",
    tiles: [
      tiles[5],
      tiles[5],
      tiles[5],
      tiles[7],
      tiles[7],
      tiles[7],
      tiles[10],
      tiles[10],
      tiles[10],
      tiles[18],
      tiles[19],
      tiles[20],
      tiles[32],
      tiles[32],
    ],
    exclusions: "",
  },
  {
    name: "44. Last Tile Drawn",
    type: "events",
    description: "Win on the last tile drawn from the wall",
    points: "8 pts",
    tiles: [],
    exclusions: "Exclude Self-Drawn",
  },
  {
    name: "45. Last Tile Claimed",
    type: "events",
    description:
      "Win on a discard after there are no more tiles left in the wall",
    points: "8 pts",
    tiles: [],
    exclusions: "",
  },
  {
    name: "46. Out with Replacement Tile",
    type: "events",
    description:
      "Win on the replacement tile drawn after melding a kong (not flower tile)",
    points: "8 pts",
    tiles: [],
    exclusions: "Exclude Self-Drawn",
  },
  {
    name: "47. Robbing the Kong",
    type: "events",
    description:
      "Win by completing a chow that someone intended to promote a pung with",
    points: "8 pts",
    tiles: [],
    exclusions: "Exclude Last Tile",
  },
  {
    name: "48. Two Concealed Kongs",
    type: "kongs",
    description: "Two concealed (but declared) kongs",
    points: "8 pts",
    tiles: [
      tiles[5],
      tiles[5],
      tiles[5],
      tiles[5],
      tiles[7],
      tiles[7],
      tiles[7],
      tiles[7],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Two Concealed Pungs, Concealed Kong",
  },
  {
    name: "49. All Pungs",
    type: "pungs",
    description: "Four pungs",
    points: "6 pts",
    tiles: [
      tiles[5],
      tiles[5],
      tiles[5],
      tiles[12],
      tiles[12],
      tiles[12],
      tiles[7],
      tiles[7],
      tiles[7],
      tiles[30],
      tiles[30],
      tiles[30],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "50. Half Flush",
    type: "other",
    description: "All sets are in tiles of one suit and honor tiles",
    points: "6 pts",
    tiles: [
      tiles[9],
      tiles[10],
      tiles[11],
      tiles[12],
      tiles[12],
      tiles[12],
      tiles[17],
      tiles[17],
      tiles[17],
      tiles[30],
      tiles[30],
      tiles[30],
      tiles[27],
      tiles[27],
    ],
    exclusions: "",
  },
  {
    name: "51. Mixed Shifted Chows",
    type: "chows",
    description:
      "Three chows, all from the same suit, each shifted up by one from the last",
    points: "6 pts",
    tiles: [
      tiles[3],
      tiles[4],
      tiles[5],
      tiles[13],
      tiles[14],
      tiles[15],
      tiles[23],
      tiles[24],
      tiles[25],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "52. All Types",
    type: "other",
    description:
      "Each of the five sets is composed of a different suit and honor such that each is represented",
    points: "6 pts",
    tiles: [
      tiles[4],
      tiles[4],
      tiles[4],
      tiles[9],
      tiles[10],
      tiles[11],
      tiles[21],
      tiles[21],
      tiles[21],
      tiles[27],
      tiles[27],
      tiles[27],
      tiles[32],
      tiles[32],
    ],
    exclusions: "",
  },
  {
    name: "53. Melded Hand",
    type: "events",
    description:
      "All sets are exposed, including the last, which is completed on a discard",
    points: "6 pts",
    tiles: [],
    exclusions: "Exclude Single Wait",
  },
  {
    name: "54. Two Dragon Pungs",
    type: "honors",
    description: "Two pungs of dragons",
    points: "6 pts",
    tiles: [
      tiles[31],
      tiles[31],
      tiles[31],
      tiles[33],
      tiles[33],
      tiles[33],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Dragon Pung",
  },
  {
    name: "55. Outside Hand",
    type: "other",
    description: "All sets contain at least one 1, 9, or honor tile",
    points: "4 pts",
    tiles: [
      tiles[0],
      tiles[1],
      tiles[2],
      tiles[9],
      tiles[10],
      tiles[11],
      tiles[17],
      tiles[17],
      tiles[17],
      tiles[28],
      tiles[28],
      tiles[28],
      tiles[26],
      tiles[26],
    ],
    exclusions: "",
  },
  {
    name: "56. Fully Concealed Hand",
    type: "events",
    description:
      "All sets are concealed, including the last, which is completed by self-draw",
    points: "4 pts",
    tiles: [],
    exclusions: "Exclude Self-Drawn",
  },
  {
    name: "57. Two Melded Kongs",
    type: "kongs",
    description: "Two exposed kongs",
    points: "4 pts",
    tiles: [
      tiles[7],
      tiles[7],
      tiles[7],
      tiles[7],
      tiles[11],
      tiles[11],
      tiles[11],
      tiles[11],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "Exclude Melded Kong",
  },
  {
    name: "58. Last Tile",
    type: "events",
    description:
      "A win on the tile that is the last of its kind due to discards and exposed sets",
    points: "4 pts",
    tiles: [],
    exclusions: "",
  },
  {
    name: "59. Dragon Pung",
    type: "honors",
    description: "Pung of any dragon",
    points: "2 pts",
    tiles: [
      tiles[32],
      tiles[32],
      tiles[32],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "60. Prevalent Wind",
    type: "honors",
    description: "Pung of the wind corresponding to the round",
    points: "2 pts",
    tiles: [
      tiles[27],
      tiles[27],
      tiles[27],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "61. Seat Wind",
    type: "honors",
    description: "Pung of the wind corresponding to the player's seat",
    points: "2 pts",
    tiles: [
      tiles[30],
      tiles[30],
      tiles[30],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "62. Concealed Hand",
    type: "events",
    description:
      "All sets concealed except the last, which is completed by discard",
    points: "2 pts",
    tiles: [],
    exclusions: "",
  },
  {
    name: "63. All Chows",
    type: "honors",
    description: "Four chows and a pair of non-honor tiles",
    points: "2 pts",
    tiles: [
      tiles[3],
      tiles[4],
      tiles[5],
      tiles[9],
      tiles[10],
      tiles[11],
      tiles[13],
      tiles[14],
      tiles[15],
      tiles[21],
      tiles[22],
      tiles[23],
      tiles[7],
      tiles[7],
    ],
    exclusions: "Exclude No Honors",
  },
  {
    name: "64. Tile Hog",
    type: "other",
    description:
      "Four identical tiles used, without forming a kong, across two or more sets",
    points: "2 pts",
    tiles: [
      tiles[3],
      tiles[3],
      tiles[3],
      tiles[2],
      tiles[3],
      tiles[4],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "65. Double Pung",
    type: "pungs",
    description: "Two pungs of the same number in different suits",
    points: "2 pts",
    tiles: [
      tiles[14],
      tiles[14],
      tiles[14],
      tiles[23],
      tiles[23],
      tiles[23],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "66. Two Concealed Pungs",
    type: "pungs",
    description: "Two unmelded pungs",
    points: "2 pts",
    tiles: [
      tiles[6],
      tiles[6],
      tiles[6],
      tiles[19],
      tiles[19],
      tiles[19],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "67. Concealed Kong",
    type: "kongs",
    description: "One unmelded kong",
    points: "2 pts",
    tiles: [
      tiles[21],
      tiles[21],
      tiles[21],
      tiles[21],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "68. All Simples",
    type: "other",
    description: "All sets use only tiles 2-8",
    points: "2 pts",
    tiles: [
      tiles[3],
      tiles[4],
      tiles[5],
      tiles[7],
      tiles[7],
      tiles[7],
      tiles[13],
      tiles[13],
      tiles[13],
      tiles[19],
      tiles[20],
      tiles[21],
      tiles[14],
      tiles[14],
    ],
    exclusions: "Exclude No Honors",
  },
  {
    name: "69. Pure Double Chow",
    type: "chows",
    description: "Two identical chows of the same suit",
    points: "1 pt",
    tiles: [
      tiles[11],
      tiles[12],
      tiles[13],
      tiles[11],
      tiles[12],
      tiles[13],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "70. Mixed Double Chow",
    type: "chows",
    description: "Two identical chows of different suits",
    points: "1 pt",
    tiles: [
      tiles[11],
      tiles[12],
      tiles[13],
      tiles[20],
      tiles[21],
      tiles[22],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "71. Short Straight",
    type: "chows",
    description: "Two consecutive chows of the same suit",
    points: "1 pt",
    tiles: [
      tiles[2],
      tiles[3],
      tiles[4],
      tiles[5],
      tiles[6],
      tiles[7],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "72. Two Terminal Chows",
    type: "chows",
    description: "One of each terminal chow from the same suit",
    points: "1 pt",
    tiles: [
      tiles[18],
      tiles[19],
      tiles[20],
      tiles[24],
      tiles[25],
      tiles[26],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "73. Pung of Terminals or Honors",
    type: "honors",
    description: "Pung of 1s, 9s, or non-special winds",
    points: "1 pt",
    tiles: [
      tiles[33],
      tiles[33],
      tiles[33],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "74. Melded Kong",
    type: "kongs",
    description: "One exposed kong",
    points: "1 pt",
    tiles: [
      tiles[12],
      tiles[12],
      tiles[12],
      tiles[12],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
      tiles[34],
    ],
    exclusions: "",
  },
  {
    name: "75. One Voided Suit",
    type: "other",
    description: "Only two of the three suits are represented",
    points: "1 pt",
    tiles: [
      tiles[9],
      tiles[10],
      tiles[11],
      tiles[15],
      tiles[15],
      tiles[15],
      tiles[21],
      tiles[21],
      tiles[21],
      tiles[30],
      tiles[30],
      tiles[30],
      tiles[23],
      tiles[23],
    ],
    exclusions: "",
  },
  {
    name: "76. No Honors",
    type: "other",
    description: "All sets use only suited tiles",
    points: "1 pt",
    tiles: [
      tiles[2],
      tiles[3],
      tiles[4],
      tiles[14],
      tiles[14],
      tiles[14],
      tiles[21],
      tiles[21],
      tiles[21],
      tiles[24],
      tiles[25],
      tiles[26],
      tiles[23],
      tiles[23],
    ],
    exclusions: "",
  },
  {
    name: "77. Edge Wait",
    type: "events",
    description: "Win after waiting only for a 3 or 7 in a terminal chow",
    points: "1 pt",
    tiles: [],
    exclusions: "",
  },
  {
    name: "78. Closed Wait",
    type: "events",
    description: "Win after waiting only for a tile in the middle of a chow",
    points: "1 pt",
    tiles: [],
    exclusions: "",
  },
  {
    name: "79. Single Wait",
    type: "events",
    description: "Win after waiting only for a tile to complete a pair",
    points: "1 pt",
    tiles: [],
    exclusions: "",
  },
  {
    name: "80. Self-Drawn",
    type: "events",
    description: "Win on a tile from the wall",
    points: "1 pt",
    tiles: [],
    exclusions: "",
  },
  {
    name: "81. Flower Tile",
    type: "events",
    description:
      "Each declared and replaced flower tile (does not count toward 8-point minimum)",
    points: "1 pt",
    tiles: [],
    exclusions: "",
  },
];

const buttons = [
  { id: 0, name: "chows", active: true },
  { id: 1, name: "pungs", active: true },
  { id: 2, name: "kongs", active: true },
  { id: 3, name: "honors", active: true },
  { id: 4, name: "other", active: true },
  { id: 5, name: "events", active: true },
];

class Guide extends Component {
  constructor(props) {
    super(props);
    this.state = {
      buttons: buttons,
      fanA: fans,
      count: fans.length,
    };
  }

  // // filter by type of fan
  handleToggle = (id) => {
    let updatedFan = [];
    let missingFan = [];
    const updatedButtons = this.state.buttons.map((button) => {
      if (button.id === id) {
        if (button.active === true) {
          missingFan = fans.filter((f) => f.type.includes(button.name));
          updatedFan = this.state.fanA.filter(
            (x) => missingFan.indexOf(x) === -1
          );
          return {
            ...button,
            active: !button.active,
          };
        } else {
          missingFan = fans.filter((f) => f.type.includes(button.name));
          const tempFan = this.state.fanA
            .concat(missingFan)
            .sort((a, b) => a.name.localeCompare(b.name));
          updatedFan = [...new Set(tempFan)];
          return {
            ...button,
            active: !button.active,
          };
        }
      } else {
        return button;
      }
    });
    this.setState({
      buttons: updatedButtons,
      fanA: updatedFan,
      count: updatedFan.length,
    });
  };

  render() {
    console.log(this.state.fanA);
    return (
      <div>
        <header>
          <Navbar />
        </header>
        <body className="mBody">
          <h1>Fan Guide</h1>
          <h3>
            There are 81 different fan, or collections of sets, that can give
            you points. Possible examples of each hand are shown below. Tiles
            with ellipses indicate an inferrable span of tiles. Blank tiles
            indicate a free space for any tile.
          </h3>
          <p>
            Use the buttons below to filter which fan are visible. Filters apply
            only when they are always implied.
          </p>
          {this.state.buttons.map((el) => (
            <button
              key={el.id}
              onClick={() => this.handleToggle(el.id)}
              className={el.active ? "pillButton" : "pillButtonDe"}
            >
              {el.name}
            </button>
          ))}
          <h4 className="htext">{this.state.count} Fan</h4>
          <div className="faq1">
            {this.state.fanA.map((a) => (
              <Fan
                key={a.name}
                name={a.name}
                description={a.description}
                points={a.points}
                tiles={a.tiles}
                exclusions={a.exclusions}
              />
            ))}
          </div>
        </body>
      </div>
    );
  }
}

export default Guide;
